CREATE TABLE IF NOT EXISTS real_estate_transaction (
    id BIGINT NOT NULL AUTO_INCREMENT,
    region_code VARCHAR(10) NOT NULL,
    legal_dong VARCHAR(60) NOT NULL,
    apt_name VARCHAR(120) NOT NULL,
    exclusive_area DECIMAL(6,2) NOT NULL,
    deal_amount BIGINT NOT NULL,
    deal_year SMALLINT NOT NULL,
    deal_month TINYINT NOT NULL,
    deal_day TINYINT NOT NULL,
    deal_ym INT NOT NULL,
    floor SMALLINT,
    build_year SMALLINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, deal_ym),
    KEY idx_region_ym (region_code, deal_ym)
) ENGINE=InnoDB
PARTITION BY RANGE (deal_ym) (
    PARTITION p2020 VALUES LESS THAN (202101),
    PARTITION p2021 VALUES LESS THAN (202201),
    PARTITION p2022 VALUES LESS THAN (202301),
    PARTITION p2023 VALUES LESS THAN (202401),
    PARTITION p2024 VALUES LESS THAN (202501),
    PARTITION p2025 VALUES LESS THAN (202601),
    PARTITION pmax VALUES LESS THAN MAXVALUE
);
